### ISSUE TITLE
Argument list too long

### ISSUE THREAD

**Issue by ajahongir** [leonid-shevtsov/headless#71]
I am having this bug every day morning. my delayed_job workers are stopping to proccess.
any idias with this, Why does this issue come?

```
shared/bundle/ruby/2.0.0/gems/activesupport-3.2.21/lib/active_support/core_ext/kernel/agnostics.rb:7:in ``'
shared/bundle/ruby/2.0.0/gems/activesupport-3.2.21/lib/active_support/core_ext/kernel/agnostics.rb:7:in ``'
shared/bundle/ruby/2.0.0/gems/headless-1.0.2/lib/headless/cli_util.rb:4:in `application_exists?'
shared/bundle/ruby/2.0.0/gems/headless-1.0.2/lib/headless/cli_util.rb:8:in `ensure_application_exists!'
shared/bundle/ruby/2.0.0/gems/headless-1.0.2/lib/headless.rb:68:in `initialize'
/lib/flight_parser/common/selenium_helper.rb:160:in `new'
/lib/flight_parser/common/selenium_helper.rb:160:in `headless'
/lib/flight_parser/asp/booking_base.rb:13:in `run'
/lib/flight_parser/flight_parser.rb:74:in `run_and_save'
/lib/jobs/datafile_base_parsing_job.rb:27:in `start_parser'
/lib/jobs/datafile_base_parsing_job.rb:10:in `perform'
shared/bundle/ruby/2.0.0/gems/delayed_job-3.0.3/lib/delayed/backend/base.rb:94:in `block in invoke_job'
shared/bundle/ruby/2.0.0/gems/delayed_job-3.0.3/lib/delayed/lifecycle.rb:60:in `call'
shared/bundle/ruby/2.0.0/gems/delayed_job-3.0.3/lib/delayed/lifecycle.rb:60:in `block in initialize'
shared/bundle/ruby/2.0.0/gems/delayed_job-3.0.3/lib/delayed/lifecycle.rb:65:in `call'
shared/bundle/ruby/2.0.0/gems/delayed_job-3.0.3/lib/delayed/lifecycle.rb:65:in `execute'
shared/bundle/ruby/2.0.0/gems/delayed_job-3.0.3/lib/delayed/lifecycle.rb:38:in `run_callbacks'
shared/bundle/ruby/2.0.0/gems/delayed_job-3.0.3/lib/delayed/backend/base.rb:91:in `invoke_job'
(eval):3:in `block in invoke_job_with_newrelic_transaction_trace'
shared/bundle/ruby/2.0.0/gems/newrelic_rpm-3.5.8.72/lib/new_relic/agent/instrumentation/controller_instrumentation.rb:268:in `block in perform_action_with_newrelic_trace'
shared/bundle/ruby/2.0.0/gems/newrelic_rpm-3.5.8.72/lib/new_relic/agent/method_tracer.rb:240:in `trace_execution_scoped'
shared/bundle/ruby/2.0.0/gems/newrelic_rpm-3.5.8.72/lib/new_relic/agent/instrumentation/controller_instrumentation.rb:263:in `perform_action_with_newrelic_trace'
(eval):2:in `invoke_job_with_newrelic_transaction_trace'
shared/bundle/ruby/2.0.0/gems/delayed_job-3.0.3/lib/delayed/worker.rb:182:in `block (2 levels) in run'
/home/capistrano/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/timeout.rb:66:in `timeout'
shared/bundle/ruby/2.0.0/gems/delayed_job-3.0.3/lib/delayed/worker.rb:182:in `block in run'
/home/capistrano/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/benchmark.rb:296:in `realtime'
shared/bundle/ruby/2.0.0/gems/delayed_job-3.0.3/lib/delayed/worker.rb:181:in `run'
shared/bundle/ruby/2.0.0/gems/delayed_job-3.0.3/lib/delayed/worker.rb:238:in `block in reserve_and_run_one_job'
shared/bundle/ruby/2.0.0/gems/delayed_job-3.0.3/lib/delayed/lifecycle.rb:60:in `call'
shared/bundle/ruby/2.0.0/gems/delayed_job-3.0.3/lib/delayed/lifecycle.rb:60:in `block in initialize'
shared/bundle/ruby/2.0.0/gems/delayed_job-3.0.3/lib/delayed/lifecycle.rb:65:in `call'
shared/bundle/ruby/2.0.0/gems/delayed_job-3.0.3/lib/delayed/lifecycle.rb:65:in `execute'
shared/bundle/ruby/2.0.0/gems/delayed_job-3.0.3/lib/delayed/lifecycle.rb:38:in `run_callbacks'
shared/bundle/ruby/2.0.0/gems/delayed_job-3.0.3/lib/delayed/worker.rb:238:in `reserve_and_run_one_job'
shared/bundle/ruby/2.0.0/gems/delayed_job-3.0.3/lib/delayed/worker.rb:166:in `block in work_off'
shared/bundle/ruby/2.0.0/gems/delayed_job-3.0.3/lib/delayed/worker.rb:165:in `times'
shared/bundle/ruby/2.0.0/gems/delayed_job-3.0.3/lib/delayed/worker.rb:165:in `work_off'
shared/bundle/ruby/2.0.0/gems/delayed_job-3.0.3/lib/delayed/worker.rb:133:in `block (4 levels) in start'
/home/capistrano/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/benchmark.rb:296:in `realtime'
shared/bundle/ruby/2.0.0/gems/delayed_job-3.0.3/lib/delayed/worker.rb:132:in `block (3 levels) in start'
shared/bundle/ruby/2.0.0/gems/delayed_job-3.0.3/lib/delayed/lifecycle.rb:60:in `call'
shared/bundle/ruby/2.0.0/gems/delayed_job-3.0.3/lib/delayed/lifecycle.rb:60:in `block in initialize'
shared/bundle/ruby/2.0.0/gems/delayed_job-3.0.3/lib/delayed/lifecycle.rb:65:in `call'
shared/bundle/ruby/2.0.0/gems/delayed_job-3.0.3/lib/delayed/lifecycle.rb:65:in `execute'
shared/bundle/ruby/2.0.0/gems/delayed_job-3.0.3/lib/delayed/lifecycle.rb:38:in `run_callbacks'
shared/bundle/ruby/2.0.0/gems/delayed_job-3.0.3/lib/delayed/worker.rb:129:in `block (2 levels) in start'
shared/bundle/ruby/2.0.0/gems/delayed_job-3.0.3/lib/delayed/worker.rb:128:in `loop'
shared/bundle/ruby/2.0.0/gems/delayed_job-3.0.3/lib/delayed/worker.rb:128:in `block in start'
shared/bundle/ruby/2.0.0/gems/delayed_job-3.0.3/lib/delayed/plugins/clear_locks.rb:7:in `call'
shared/bundle/ruby/2.0.0/gems/delayed_job-3.0.3/lib/delayed/plugins/clear_locks.rb:7:in `block (2 levels) in '
shared/bundle/ruby/2.0.0/gems/delayed_job-3.0.3/lib/delayed/lifecycle.rb:78:in `call'
shared/bundle/ruby/2.0.0/gems/delayed_job-3.0.3/lib/delayed/lifecycle.rb:78:in `block (2 levels) in add'
shared/bundle/ruby/2.0.0/gems/delayed_job-3.0.3/lib/delayed/lifecycle.rb:60:in `call'
shared/bundle/ruby/2.0.0/gems/delayed_job-3.0.3/lib/delayed/lifecycle.rb:60:in `block in initialize'
shared/bundle/ruby/2.0.0/gems/delayed_job-3.0.3/lib/delayed/lifecycle.rb:78:in `call'
shared/bundle/ruby/2.0.0/gems/delayed_job-3.0.3/lib/delayed/lifecycle.rb:78:in `block in add'
shared/bundle/ruby/2.0.0/gems/delayed_job-3.0.3/lib/delayed/lifecycle.rb:65:in `call'
shared/bundle/ruby/2.0.0/gems/delayed_job-3.0.3/lib/delayed/lifecycle.rb:65:in `execute'
shared/bundle/ruby/2.0.0/gems/delayed_job-3.0.3/lib/delayed/lifecycle.rb:38:in `run_callbacks'
shared/bundle/ruby/2.0.0/gems/delayed_job-3.0.3/lib/delayed/worker.rb:127:in `start'
shared/bundle/ruby/2.0.0/gems/delayed_job-3.0.3/lib/delayed/command.rb:101:in `run'
shared/bundle/ruby/2.0.0/gems/delayed_job-3.0.3/lib/delayed/command.rb:89:in `block in run_process'
shared/bundle/ruby/2.0.0/gems/daemons-1.1.9/lib/daemons/application.rb:255:in `call'
shared/bundle/ruby/2.0.0/gems/daemons-1.1.9/lib/daemons/application.rb:255:in `block in start_proc'
shared/bundle/ruby/2.0.0/gems/daemons-1.1.9/lib/daemons/daemonize.rb:82:in `call'
shared/bundle/ruby/2.0.0/gems/daemons-1.1.9/lib/daemons/daemonize.rb:82:in `call_as_daemon'
shared/bundle/ruby/2.0.0/gems/daemons-1.1.9/lib/daemons/application.rb:259:in `start_proc'
shared/bundle/ruby/2.0.0/gems/daemons-1.1.9/lib/daemons/application.rb:296:in `start'
shared/bundle/ruby/2.0.0/gems/daemons-1.1.9/lib/daemons/controller.rb:70:in `run'
shared/bundle/ruby/2.0.0/gems/daemons-1.1.9/lib/daemons.rb:197:in `block in run_proc'
shared/bundle/ruby/2.0.0/gems/daemons-1.1.9/lib/daemons/cmdline.rb:109:in `call'
shared/bundle/ruby/2.0.0/gems/daemons-1.1.9/lib/daemons/cmdline.rb:109:in `catch_exceptions'
shared/bundle/ruby/2.0.0/gems/daemons-1.1.9/lib/daemons.rb:196:in `run_proc'
shared/bundle/ruby/2.0.0/gems/delayed_job-3.0.3/lib/delayed/command.rb:87:in `run_process'
shared/bundle/ruby/2.0.0/gems/delayed_job-3.0.3/lib/delayed/command.rb:76:in `daemonize'
script/delayed_job:5:in `
```

**Comment by ajahongir** [comment]
it seams issue coming here  - https://github.com/leonid-shevtsov/headless/blob/master/lib/headless/cli_util.rb#L4

**Comment by leonid-shevtsov** [comment]
That's a weird issue, because Headless is tested on Travis against Ruby 2.0, and seems to be doing fine, and the ActiveSupport extension should not be interfering.

Does it repro on the latest Headless version? What is the patchlevel of Ruby that you are using?

**Comment by ajahongir** [comment]
having this issue last 3 years. before it was raising sometimes but now every after 20 hours of working. so now I restart my application 2 times a day to not have this issue.
before I used to ubuntu 10.04. then 12.04 now using 16.04 still having this issue. Headless every time us latest version.

**Comment by leonid-shevtsov** [comment]
Can you provide your Ruby version (`ruby --version`) and ideally your gem list (`bundle list`)?
